# Generated by Django 4.1.2 on 2022-10-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='desscription',
            field=models.TextField(blank=True),
        ),
    ]
