# Generated by Django 4.1.2 on 2022-10-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_product_composition_product_desscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_drink',
            name='category',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='category_food',
            name='category',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
