# Generated by Django 4.1.2 on 2022-10-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_drink_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weitht',
            field=models.IntegerField(default=0),
        ),
    ]
