# Generated by Django 4.1.2 on 2022-10-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_dish_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='category')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ManyToManyField(to='menu.category'),
        ),
    ]
