# Generated by Django 4.1.2 on 2022-10-21 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_product_weitht'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='drink',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.type_drink'),
        ),
    ]
