# Generated by Django 4.1.2 on 2022-10-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_category_dish_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default=True, max_length=50, verbose_name='category'),
        ),
    ]
