# Generated by Django 4.1.2 on 2022-10-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_type_drink_drink_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_drink',
            name='type',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
