# Generated by Django 4.1.2 on 2022-10-21 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_type_drink_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type_drink',
            old_name='type',
            new_name='types',
        ),
    ]
