# Generated by Django 4.1.2 on 2022-10-21 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_rename_type_type_drink_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='type',
            new_name='types',
        ),
    ]
