# Generated by Django 4.1.2 on 2022-10-21 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_rename_type_drink_types'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type_drink',
            new_name='Kind_drink',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='types',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='kind_drink',
            old_name='types',
            new_name='kind',
        ),
    ]
