# Generated by Django 4.1.2 on 2022-10-21 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_rename_type_drink_kind_drink_rename_types_drink_kind_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kind_drink',
            options={'verbose_name': 'drink kind', 'verbose_name_plural': 'drink kinds'},
        ),
    ]
